site_name: GLI Docs
repo_url: https://github.com/domino-team/docs/
site_description: This is the docs for GLI mini router, OpenWrt, OpenVPN
site_favicon: null
copyright: null
google_analytics: null
site_dir: 'site'
docs_dir: 'docs'
theme: 'mkdocs'


pages:
- Index: 'index.md'
- Home:
    - 'About Us' : 'about.md'
    - 'Services' : 'service.md'
- DIY:
    - 'Working with UART serial' : 'diy/serial.md'
    - 'working with uboot' : 'diy/uboot.md'
- OpenWrt:
    - 'OpenVPN' : 'openwrt/openvpn.md'

- Domino Kit:
  
  - 'Getting Started' : 'domino/index.md'
  - - - - 
  - 'Domore Core' : 'domino/hardware/core.md'
  - 'Domino Pi Baseboard': 'domino/pi/pi.md'
    - 'Domino Pi - Single Eth board': 'domino/pi/single_eth.md'
    - 'Domino Pi - Due Eth board': 'domino/pi/dual_eth.md'
    - 'Domino Pi - Signle USB board': 'domino/pi/single_usb.md'
    - 'Domino Pi - 3xUSB+MicroSD combo': 'domino/pi/usb_combo.md'
    - 'Domino Pi - I2S board': 'domino/pi/i2s.md'
    - 'Domino Pi - SPI/JTAG': 'domino/pi/spi_jtag.md'
    - 'Domino Pi - LED': 'domino/pi/led.md'
    - 'Domino Qi Mini' : 'domino/qi/mini.md'
    - 'Domino Qi baseboard': 'domino/qi/base.md'
  - 'Domino Pi Instructions':
    - 'Using the firmware': 'domino/pi/using.md'
    - 'Compile firmware': 'domino/pi/compile.md'
    - 'Flashing and debricking': 'domino/pi/flashing.md'
    - 'Playing Music': 'domino/pi/audio.md'
    - 'Working with Serial': 'domino/pi/serial.md'
    - 'Debricking using SPI/JTAG board': 'domino/pi/spi.md'
  - 'Domino Qi Instructions':
    - 'Getting Started': 'domino/qi/index.md'
    - 'Using Arduino or Linino Firmware': 'domino/qi/arduino-yun.md'
    - 'Using NodeJS and LininoIO': 'domino/qi/nodejs.md'
    - 'Using Serial': 'domino/qi/serial.md'